# @format

version: '3.1'

services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:12.1
    volumes:
      - ./drupal-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    restart: always
